services:
    nginx:
        build: ./nginx/
        ports:
        - 80:80
        depends_on:
            - php
        networks:
            - securespend
    php:
        build: ./php_code/
        depends_on:
            - mysqldb
        networks:
            - securespend
        environment:
            MYSQL_HOST: mysql
            MYSQL_PORT: 3306
            MYSQL_USER: admin_secure
            MYSQL_PASSWORD: g
            MYSQL_DATABASE: securespend
            OIDC_ISSUER_URL: your-issuer-url
            OIDC_CLIENT_ID: your-client-id
            OIDC_CLIENT_SECRET: your-client-secret
    mysqldb:    
        image: mysql
        container_name: mysql
        volumes: 
            - mysql-data:/var/lib/mysql
            - ./mysql/setup.sql:/docker-entrypoint-initdb.d/001-init.sql
        environment:  
            MYSQL_ROOT_PASSWORD: secretpassword
            MYSQL_DATABASE: securespend
            MYSQL_USER: admin_secure
            MYSQL_PASSWORD: g
        networks:
            - securespend

networks:
    securespend:
        driver: bridge

volumes:
    mysql-data: